sectors:
- name: Energy
  etf: XLE
  keyword: Energy
  override_tickers: []
- name: Materials
  etf: XLB
  keyword: Materials
  override_tickers: []
- name: Industrials
  etf: XLI
  keyword: Sector
  override_tickers: []
- name: Consumer Discretionary
  etf: XLY
  keyword: Consumer
  override_tickers: []
- name: Consumer Staples
  etf: XLP
  keyword: Consumer
  override_tickers: []
- name: Healthcare
  etf: XLV
  keyword: Sector
  override_tickers: []
- name: Financials
  etf: XLF
  keyword: Sector
  override_tickers: []
- name: Information Technology
  etf: XLK
  keyword: Tech
  override_tickers: []
- name: Communication Services
  etf: XLC
  keyword: Sector
  override_tickers: []
- name: Utilities
  etf: XLU
  keyword: Utilities
  override_tickers: []
- name: Real Estate
  etf: XLRE
  keyword: Reits
  override_tickers: []
max_firms_per_sector: 3
