sectors:
  - name: Energy
    etf: XLK
    keyword: Energy
    override_tickers: ["XOM", "CVX", "SLB"]

  - name: Materials
    etf: XLB
    keyword: Materials
    override_tickers: ["DD", "NEM", "FCX"]

  - name: Industrials
    etf: XLI
    keyword: Industrials
    override_tickers: ["BA", "CAT", "HON"]

  - name: Consumer Discretionary
    etf: XLY
    keyword: Consumer Discretionary
    override_tickers: ["AMZN", "TSLA", "NKE"]

  - name: Consumer Staples
    etf: XLP
    keyword: Consumer Staples
    override_tickers: ["PG", "KO", "WMT"]
  
  - name: Health Care
    etf: XLV
    keyword: Health Care
    override_tickers: ["JNJ", "PFE", "MRK"]

  - name: Financials
    etf: XLF
    keyword: Financials
    override_tickers: ["JPM", "BAC", "WFC"]

  - name: Information Technology
    etf: XLK
    keyword: Information Technology
    override_tickers: ["AAPL", "MSFT", "GOOGL"]

  - name: Communication Services
    etf: XLC
    keyword: Communication Services
    override_tickers: ["FB", "GOOGL", "NFLX"]
  
  - name: Utilities
    etf: XLU
    keyword: Utilities
    override_tickers: ["DUK", "SO", "NEE"]

  - name: Real Estate 
    etf: XLF
    keyword: Real Estate
    override_tickers: ["AMT", "PLD", "SPG"]
    
max_firms_per_sector: 3