sectors:
- name: Energy
  etf: XLE
  keyword: data-center power demand
  override_tickers: ["XOM", "CVX", "COP", "WMB", "EOG", "KMI", "MPC", "OKE", "SLB", "PSX"]

- name: Materials
  etf: XLB
  keyword: critical minerals
  override_tickers: ["FCX", "LIN", "SHW", "ECL", "CTVA", "NEM", "APD", "VMC", "MLM", "DD"]

- name: Industrials
  etf: XLI
  keyword: reshoring
  override_tickers: ["GE", "RTX", "UBER", "CAT", "BA", "HON", "UNP", "DE", "GEV", "ETN"]

- name: Utilities
  etf: XLU
  keyword: grid modernization
  override_tickers: ["NEE", "SO", "DUK", "EXC", "XEL", "AEP", "SRE", "D", "CEG", "VST"]
 
- name: Healthcare
  etf: XLV
  keyword: elder-care labor shortage
  override_tickers: ["LLY", "JNJ", "ABBV", "UNH", "ABT", "MRK", "ISRG", "TMO", "AMGN", "BSX"]

- name: Financials
  etf: XLF
  keyword: digital deregulation
  override_tickers: ["BRK.B", "JPM", "V", "MA", "BAC", "WFC", "GS", "AXP", "MS", "SPGI"]
  
- name: Consumer Discretionary
  etf: XLY
  keyword: e-commerce expansion
  override_tickers: ["AMZN", "TSLA", "HD", "BKNG", "MCD", "TJX", "LOW", "SBUX", "ORLY", "NKE"]
  
- name: Consumer Staples
  etf: XLP
  keyword: pricing power
  override_tickers: ["COST", "WMT", "PG", "KO", "PM", "MDLZ", "MO", "CL", "PEP", "TGT"]

- name: Information Technology
  etf: XLK
  keyword: generative AI
  override_tickers: ["MSFT", "AAPL", "NVDA", "AVGO", "ORCL", "PLTR", "CSCO", "CRM", "IBM", "INTU"]

- name: Communication Services
  etf: XLC
  keyword: streaming bundling
  override_tickers: ["META", "GOOGL", "NFLX", "GOOG", "DIS", "TTWO", "LYV", "CHTR", "EA", "T"]

- name: Real Estate
  etf: XLRE
  keyword: office-to-resi conversion
  override_tickers: ["PLD", "AMT", "WELL", "EQIX", "DLR", "O", "SPG", "PSA", "CCI", "CBRE"]
  
max_firms_per_sector: 10